### ISSUE TITLE
New topic: preview button throws JavaScript Error (Wrong AJAX)

### ISSUE THREAD

**Issue by lisardo2** [DavidBruchmann/typo3_forum#13]
http://typo3forum-transfer.local/index.php?eID=typo3_forum&tx_typo3forum_ajax[controller]=Post&tx_typo3forum_ajax[action]=preview&id=53 => Page not found.

**Comment by DavidBruchmann** [comment]
BTW: the link is only working on the page and not separated.
Also it shows the preview inline below the textarea, perhaps you missed it somehow?

**Comment by DavidBruchmann** [comment]
Bitte wieder öffnen wenn noch aktuell.
