### ISSUE TITLE
topic list: link to author is shown in entities

### ISSUE THREAD

**Issue by lisardo2** [DavidBruchmann/typo3_forum#14]
the text looks like this: 
&lt;a href="/index.php?id=50&tx_typo3forum_pi1%5Buser%5D=263&tx_typo3forum_pi1%5Bcontroller%5D=User&tx_typo3forum_pi1%5Baction%5D=show&cHash=e1ece88e3280b36763d4e833eddf6ce6" class="user-link nav-pills-inline" title="linzenkirchner"&gt;linzenkir... &lt;i class="user_onlinepoint iconset-8-user-offline" data-uid="263"&gt;&lt;/i&gt; &lt;/a&gt;

i presume the new security feature in fluid.

**Comment by lisardo2** [comment]
Hallo David,

bei mir sieht es so aus:




Gruß
Peter

> Am 08.08.2018 um 13:22 schrieb David Bruchmann <notifications@github.com>:
> 
> You mean the shortend / cropped name?
> That's probably a setting
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
-----------------------------------------------
Peter Linzenkirchner
Lisardo EDV-Beratung
Katharinengasse 20, Rückgebäude,
Eingang Bleigäßchen 5
86150 Augsburg
Tel. +49-821-150565, Fax +49-821-150595
http://typo3-lisardo.de
info@lisardo.de
-----------------------------------------------

**Comment by DavidBruchmann** [comment]
in diesem template erledigt
