### ISSUE TITLE
Use proper extension name in FE plugin

### ISSUE THREAD

**Issue by schams-net** [DavidBruchmann/typo3_forum#32]
I am not sure, if this is different in other languages (e.g. German), but in the English, the dropdown boxes show `typo3_forum` as the extension name, when someone adds the extension to a page in the BE.

If this is not intended, it might be useful to consider a proper extension name such as "TYPO3 Forum" or similar, rather than the technical terminology (extension key).

![screenshot0002](https://user-images.githubusercontent.com/3617721/45156632-1ffb5f80-b222-11e8-98f1-c398f8c13fe2.png)

**Comment by DavidBruchmann** [comment]
Translation-file issue probably

**Comment by DavidBruchmann** [comment]
statically changed in ext_tables.php.
Still can be replaced by translation solution when #37 will be solved.
